# condense_wildcard_suffixes = true
# fn_single_line = true
force_explicit_abi = true
# format_macro_matchers = true
hard_tabs = true
# hex_literal_case = "Lower"
# imports_layout = "HorizontalVertical"
# match_block_trailing_comma = true
max_width = 250
# imports_granularity = "Module"
newline_style = "Unix"
# normalize_commands = true
# normalize_doc_attributes = true
# overflow_delimited_expr = true
# reorder_impl_items = true
reorder_imports = true
# group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
